#!/bin/bash

# Get the Python file name from the environment variable
PYFILE=${PYFILE:-""}

if [ -z "$PYFILE" ]; then
  echo "Error: PYFILE environment variable is not set"
  exit 1
fi

# Compile the Python file
python -m py_compile $PYFILE

# Rename the compiled file to add the ".pyc" suffix
mv __pycache__/${PYFILE%.py}.cpython-*.pyc ${PYFILE}c

# Remove the __pycache__ directory created by the compilation
rm -rf __pycache__
#!/usr/bin/python3
python3 -m compileall -b $PYFILE
